import { registerCaptureIpc } from "./capture";
import { registerCursorIpc } from "./cursor";
import { registerScreenCaptureIpc } from "./screenCapture";
import { registerCameraBubbleIpc } from "./cameraBubble";
import { registerRecordingDockIpc } from "./recordingDock";
import { registerAreaSelectIpc } from "./areaSelect";
import { registerAnnotationIpc } from "./annotation";
import { registerRecordingIpc } from "./recording";
import { registerLibraryIpc } from "./library";
import { registerSettingsIpc } from "./settings";
import { registerAppsIpc } from "./apps";
import { registerAiIpc } from "./ai";
import { registerTranscriptionIpc } from "./transcription";
import { registerWindowIpc } from "./window";
import { registerAuthIpc } from "./auth";
import { registerTeamsIpc } from "./teams";
import { registerProjectManagersIpc } from "./projectManagers";
import { registerPersonasIpc } from "./personas";
import { registerStorageIpc } from "./storage";

export function registerIpcHandlers(): void {
  registerCaptureIpc();
  registerCursorIpc();
  registerScreenCaptureIpc();
  registerCameraBubbleIpc();
  registerRecordingDockIpc();
  registerAreaSelectIpc();
  registerAnnotationIpc();
  registerRecordingIpc();
  registerLibraryIpc();
  registerSettingsIpc();
  registerAppsIpc();
  registerAiIpc();
  registerTranscriptionIpc();
  registerWindowIpc();
  registerAuthIpc();
  registerTeamsIpc();
  registerProjectManagersIpc();
  registerPersonasIpc();
  registerStorageIpc();
}
