
export const Channels = {
  capture: {
    listTargets: "capture:listTargets",
  },
  cursor: {
    apply: "cursor:apply",
    restore: "cursor:restore",
  },
  annotation: {
    open: "annotation:open",
    close: "annotation:close",
    isOpen: "annotation:isOpen",
    setTool: "annotation:setTool",
    setColor: "annotation:setColor",
    undo: "annotation:undo",
    redo: "annotation:redo",
    clear: "annotation:clear",
    reportHistoryState: "annotation:reportHistoryState",
    stateChanged: "annotation:stateChanged",
    command: "annotation:command",
    historyStateChanged: "annotation:historyStateChanged",
    overlayOpenChanged: "annotation:overlayOpenChanged",
  },
  recording: {
    save: "recording:save",
    saveAudio: "recording:saveAudio",
    saveCompleted: "recording:saveCompleted",
    saveFailed: "recording:saveFailed",
  },
  library: {
    list: "library:list",
    get: "library:get",
    delete: "library:delete",
    trim: "library:trim",
    search: "library:search",
    rename: "library:rename",
    setTranscript: "library:setTranscript",
  },
  settings: {
    getSaveDir: "settings:getSaveDir",
    setSaveDir: "settings:setSaveDir",
    pickSaveDir: "settings:pickSaveDir",
    showItemInFolder: "settings:showItemInFolder",
    listLlmProfiles: "settings:listLlmProfiles",
    getActiveLlmProfileId: "settings:getActiveLlmProfileId",
    saveLlmProfile: "settings:saveLlmProfile",
    deleteLlmProfile: "settings:deleteLlmProfile",
    setActiveLlmProfile: "settings:setActiveLlmProfile",
    defaultProfileTemplate: "settings:defaultProfileTemplate",
    getRecordSettings: "settings:getRecordSettings",
    setRecordSettings: "settings:setRecordSettings",
    getMeetingSettings: "settings:getMeetingSettings",
    setMeetingSettings: "settings:setMeetingSettings",
    getWhisperModel: "settings:getWhisperModel",
    setWhisperModel: "settings:setWhisperModel",
    getWhisperModelStatuses: "settings:getWhisperModelStatuses",
    downloadWhisperModel: "settings:downloadWhisperModel",
    deleteWhisperModel: "settings:deleteWhisperModel",
    getWhisperModelsDir: "settings:getWhisperModelsDir",
    openWhisperModelsDir: "settings:openWhisperModelsDir",
  },
  ai: {
    summarize: "ai:summarize",
    chat: "ai:chat",
    testConnection: "ai:testConnection",
  },
  transcription: {
    transcribe: "transcription:transcribe",
    transcribePcm: "transcription:transcribePcm",
    cancel: "transcription:cancel",
  },
  window: {
    minimize: "window:minimize",
    close: "window:close",
  },
  auth: {
    getSession: "auth:getSession",
    login: "auth:login",
    submitManualCode: "auth:submitManualCode",
    cancelLogin: "auth:cancelLogin",
    logout: "auth:logout",
    sessionChanged: "auth:sessionChanged",
  },
} as const;
