
export const Channels = {
  capture: {
    listTargets: "capture:listTargets",
    getPermissionStatus: "capture:getPermissionStatus",
    openScreenRecordingSettings: "capture:openScreenRecordingSettings",
  },
  cursor: {
    apply: "cursor:apply",
    restore: "cursor:restore",
    startCapture: "cursor:startCapture",
    stopCapture: "cursor:stopCapture",
  },
  screenCapture: {
    start: "screenCapture:start",
    stop: "screenCapture:stop",
  },
  annotation: {
    open: "annotation:open",
    isOpen: "annotation:isOpen",
    getState: "annotation:getState",
    setTool: "annotation:setTool",
    setColor: "annotation:setColor",
    setWidth: "annotation:setWidth",
    setOpacity: "annotation:setOpacity",
    setFadeMs: "annotation:setFadeMs",
    undo: "annotation:undo",
    redo: "annotation:redo",
    clear: "annotation:clear",
    reportHistoryState: "annotation:reportHistoryState",
    setStrokeActive: "annotation:setStrokeActive",
    stateChanged: "annotation:stateChanged",
    command: "annotation:command",
    historyStateChanged: "annotation:historyStateChanged",
    overlayOpenChanged: "annotation:overlayOpenChanged",
  },
  recording: {
    save: "recording:save",
    saveAudio: "recording:saveAudio",
    saveProgress: "recording:saveProgress",
    cancelSave: "recording:cancelSave",
    saveCompleted: "recording:saveCompleted",
    saveFailed: "recording:saveFailed",
  },
  library: {
    list: "library:list",
    get: "library:get",
    delete: "library:delete",
    deleteMany: "library:deleteMany",
    search: "library:search",
    rename: "library:rename",
    setTranscript: "library:setTranscript",
    pickFiles: "library:pickFiles",
    importFiles: "library:importFiles",
    importProgress: "library:importProgress",
  },
  settings: {
    getSaveDir: "settings:getSaveDir",
    setSaveDir: "settings:setSaveDir",
    pickSaveDir: "settings:pickSaveDir",
    showItemInFolder: "settings:showItemInFolder",
    listLlmProfiles: "settings:listLlmProfiles",
    saveLlmProfile: "settings:saveLlmProfile",
    deleteLlmProfile: "settings:deleteLlmProfile",
    defaultProfileTemplate: "settings:defaultProfileTemplate",
    getRecordSettings: "settings:getRecordSettings",
    setRecordSettings: "settings:setRecordSettings",
    getMeetingSettings: "settings:getMeetingSettings",
    setMeetingSettings: "settings:setMeetingSettings",
    getWhisperModel: "settings:getWhisperModel",
    setWhisperModel: "settings:setWhisperModel",
    getWhisperModelStatuses: "settings:getWhisperModelStatuses",
    downloadWhisperModel: "settings:downloadWhisperModel",
    deleteWhisperModel: "settings:deleteWhisperModel",
    getWhisperModelsDir: "settings:getWhisperModelsDir",
    openWhisperModelsDir: "settings:openWhisperModelsDir",
    getUseDoculigentModel: "settings:getUseDoculigentModel",
    setUseDoculigentModel: "settings:setUseDoculigentModel",
    getTranscriptionByokProfileId: "settings:getTranscriptionByokProfileId",
    setTranscriptionByokProfileId: "settings:setTranscriptionByokProfileId",
    getAutoTranscribeSettings: "settings:getAutoTranscribeSettings",
    setAutoTranscribeSettings: "settings:setAutoTranscribeSettings",
  },
  ai: {
    summarize: "ai:summarize",
    chat: "ai:chat",
    testConnection: "ai:testConnection",
  },
  apps: {
    list: "apps:list",
    save: "apps:save",
    delete: "apps:delete",
    testConnection: "apps:testConnection",
    githubCreateIssue: "apps:githubCreateIssue",
    githubCommentIssue: "apps:githubCommentIssue",
    slackPostMessage: "apps:slackPostMessage",
  },
  transcription: {
    transcribe: "transcription:transcribe",
    transcribePcm: "transcription:transcribePcm",
    cancel: "transcription:cancel",
  },
  window: {
    minimize: "window:minimize",
    close: "window:close",
    toggleMaximize: "window:toggleMaximize",
    isMaximized: "window:isMaximized",
    maximizeChanged: "window:maximizeChanged",
  },
  auth: {
    getSession: "auth:getSession",
    login: "auth:login",
    submitManualCode: "auth:submitManualCode",
    cancelLogin: "auth:cancelLogin",
    logout: "auth:logout",
    sessionChanged: "auth:sessionChanged",
  },
  teams: {
    create: "teams:create",
    list: "teams:list",
    get: "teams:get",
    inviteMember: "teams:inviteMember",
    removeMember: "teams:removeMember",
    delete: "teams:delete",
    listFiles: "teams:listFiles",
    presignDownload: "teams:presignDownload",
    setFileStatus: "teams:setFileStatus",
    permanentlyDeleteFile: "teams:permanentlyDeleteFile",
    uploadFile: "teams:uploadFile",
    uploadProgress: "teams:uploadProgress",
    downloadToLibrary: "teams:downloadToLibrary",
    listSyncedFileIds: "teams:listSyncedFileIds",
  },
  pm: {
    list: "pm:list",
    save: "pm:save",
    delete: "pm:delete",
    generateInsight: "pm:generateInsight",
    generateOverallInsight: "pm:generateOverallInsight",
    markAutoProcessed: "pm:markAutoProcessed",
    run: "pm:run",
  },
  persona: {
    list: "persona:list",
    save: "persona:save",
    delete: "persona:delete",
  },
  storage: {
    getPreference: "storage:getPreference",
    setPreference: "storage:setPreference",
    listTeams: "storage:listTeams",
    createTeam: "storage:createTeam",
    deleteTeam: "storage:deleteTeam",
    listFiles: "storage:listFiles",
    uploadFile: "storage:uploadFile",
    uploadProgress: "storage:uploadProgress",
    downloadToLibrary: "storage:downloadToLibrary",
    deleteFile: "storage:deleteFile",
    getShareableLink: "storage:getShareableLink",
    getCachedShareLink: "storage:getCachedShareLink",
  },
} as const;
